spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-lht-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-lht-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/       