spring: 
    profiles: 
        active:
           - dev
---
server: 
    port: 8201
spring:
    profiles: dev
    application:
        name: service-config-client-dev222
eureka:
    client: 
        service-url: 
            defaultZone: http://127.0.0.1:8761/eureka/
---
server: 
    port: 8202
spring:
    profiles: test
    application:
        name: service-config-client-test
eureka:
    client: 
        service-url: 
            defaultZone: http://127.0.0.1:8761/eureka/